version: "3.7"

services:
  app:
    image: byu-tools
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://postgres:example@postgres/byu_tools
  postgres:
    image: byu-tools-db
    volumes:
      - byu-tools-data:/var/lib/postgresql/data

volumes:
  byu-tools-data:
